name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Needed for us to push to GHCR

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/sse-groupies/authentication:latest .
          docker push ghcr.io/sse-groupies/authentication:latest

      # Deploy to Azure
      - name: Deploy to Azure
        run: |
          az container create \
            --resource-group SSE-Auth \
            --name auth-service \
            --image ghcr.io/sse-groupies/authentication:latest \
            --ports 5001 \
            --dns-name-label sse-auth-service-2 \ # If we keep changing this, can add a date and time variable instead of -2
            --os-type Linux \
            --cpu 1 \
            --memory 1
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

